### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by saengowp** [PyThaiNLP/pythainlp#164]
**Description**

`tensorflow` dependency missing when calling `romanization(_, 'thai2rom')`.

**Step to reproduce**

type following command.

````python
>>> from pythainlp import romanization
>>> romanization("แมว", "thai2rom")
````

*Result:*
````
Collecting keras
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting numpy>=1.9.1 (from keras)
  Downloading https://files.pythonhosted.org/packages/38/39/f73e104d44f19a6203e786d5204532e214443ea2954917b27f3229e7639b/numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 4.2MB/s 
Collecting pyyaml (from keras)
Collecting keras-preprocessing>=1.0.5 (from keras)
  Using cached https://files.pythonhosted.org/packages/fc/94/74e0fa783d3fc07e41715973435dd051ca89c550881b3454233c39c73e69/Keras_Preprocessing-1.0.5-py2.py3-none-any.whl
Collecting scipy>=0.14 (from keras)
  Downloading https://files.pythonhosted.org/packages/80/39/066ecde98f373430bf7a39a02d91c7075b01ef4fc928456e8e31577342d6/scipy-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (26.6MB)
    100% |████████████████████████████████| 26.6MB 1.6MB/s 
Collecting keras-applications>=1.0.6 (from keras)
  Using cached https://files.pythonhosted.org/packages/3f/c4/2ff40221029f7098d58f8d7fb99b97e8100f3293f9856f0fb5834bef100b/Keras_Applications-1.0.6-py2.py3-none-any.whl
Collecting h5py (from keras)
  Downloading https://files.pythonhosted.org/packages/8e/fd/2ca5c4f4ed33ac4178f9c4d551e3946ab480866e3cd67a65a67a4bb35367/h5py-2.9.0-cp37-cp37m-manylinux1_x86_64.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 17.9MB/s 
Requirement already satisfied: six>=1.9.0 in ./env/lib/python3.7/site-packages (from keras) (1.12.0)
Installing collected packages: numpy, pyyaml, keras-preprocessing, scipy, h5py, keras-applications, keras
Successfully installed h5py-2.9.0 keras-2.2.4 keras-applications-1.0.6 keras-preprocessing-1.0.5 numpy-1.15.4 pyyaml-3.13 scipy-1.2.0
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: numpy in ./env/lib/python3.7/site-packages (1.15.4)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/pythainlp/romanization/__init__.py", line 19, in romanization
    from pythainlp.romanization.thai2rom import thai2rom
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/pythainlp/romanization/thai2rom.py", line 14, in <module>
    from keras.models import Model, load_model
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/tmp/pythaithai2rombug/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
````

**Workaround**

Manually installing `tensorflow` using pip.

**Affected version**

pythainlp-1.7.1

**Comment by wannaphongcom** [comment]
Can you update TensorFlow ?

`pip install -U tensorflow`

**Comment by saengowp** [comment]
Workaround fixed the problem. However, Shouldn't the library automatically install `tensorflow` by itself?

**Comment by wannaphongcom** [comment]
@saengowp Yes, we will remove automatically install in PyThaiNLP 2.0.
