### ISSUE TITLE
ImportError: No module named multi_cut

### ISSUE THREAD

**Issue by loretoparisi** [PyThaiNLP/pythainlp#189]
I have installed the latest version available with `pip` and installed via `pip install pythainlp -U`.
```
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/loretoparisi/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package omw to
[nltk_data]     /Users/loretoparisi/nltk_data...
[nltk_data]   Unzipping corpora/omw.zip.
Traceback (most recent call last):
  File "dictionary.py", line 13, in <module>
    w2w = Word2word(codes[0], codes[1], dict_path=dict_path)
  File "/word2word/word2word/word2word.py", line 12, in __init__
    self.word2x, self.y2word, self.x2ys = download_or_load(lang1, lang2, dict_path)
  File "/word2word/word2word/utils.py", line 52, in download_or_load
    word2x, y2word, x2ys = pickle.load(open(fpath, 'rb'))
  File "/usr/local/lib/python2.7/site-packages/zodbpickle/pickle_2.py", line 1525, in load
    return Unpickler(file).load()
  File "/usr/local/lib/python2.7/site-packages/zodbpickle/pickle_2.py", line 881, in load
    dispatch[key](self)
  File "/usr/local/lib/python2.7/site-packages/zodbpickle/pickle_2.py", line 1142, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/site-packages/zodbpickle/pickle_2.py", line 1176, in find_class
    __import__(module)
ImportError: No module named multi_cut
```
This error was originated in https://github.com/zopefoundation/zodbpickle/issues/45

**Comment by wannaphongcom** [comment]
PyThaiNLP 2.0 supports Python 3.6+. Some functions may work with older version of Python 3, but it is not well-tested and will not be supported.

Python 2.7+ users can use PyThaiNLP 1.6.

`pip install pythainlp==1.6.0.7 `

**Comment by loretoparisi** [comment]
@wannaphongcom thanks, I have downgraded to the previous version.
