### ISSUE TITLE
Can't from  from pythainlp.tokenize import  on Mac OS X 

### ISSUE THREAD

**Issue by luoying1105** [PyThaiNLP/pythainlp#57]
have some problem like this
Traceback (most recent call last):
  File "/Users/ying/PycharmProjects/untitled/SentenceAligner/auto_Pretreatment/taiyu.py", line 1, in <module>
    from pythainlp.tokenize import tcc
  File "/Users/ying/anaconda/lib/python3.6/site-packages/pythainlp/__init__.py", line 15, in <module>
    from pythainlp.date import now
  File "/Users/ying/anaconda/lib/python3.6/site-packages/pythainlp/date/__init__.py", line 3, in <module>
    import icu
  File "/Users/ying/anaconda/lib/python3.6/site-packages/icu/__init__.py", line 40, in <module>
    from .docs import *
  File "/Users/ying/anaconda/lib/python3.6/site-packages/icu/docs.py", line 23, in <module>
    from _icu import *
ImportError: dlopen(/Users/ying/anaconda/lib/python3.6/site-packages/_icu.cpython-36m-darwin.so, 2): Library not loaded: libicui18n.54.dylib
  Referenced from: /Users/ying/anaconda/lib/python3.6/site-packages/_icu.cpython-36m-darwin.so
  Reason: image not found

**Comment by wannaphongcom** [comment]
I apologize for any inconvenience this may cause you.We do delete pyicu from requirements in PyThaiNLP 1.6 (alpha version). You can install PyThaiNLP 1.6.
``pip install https://github.com/PyThaiNLP/pythainlp/archive/dev.zip``

**Comment by luoying1105** [comment]
sorry,i still have some problem
Traceback (most recent call last):
  File "/Users/ying/PycharmProjects/untitled/SentenceAligner/tools/segemen.py", line 1, in <module>
    from pythainlp import word_tokenize
  File "/Users/ying/anaconda3/envs/untitled1/lib/python3.6/site-packages/pythainlp/__init__.py", line 15, in <module>
    from pythainlp.date import now
  File "/Users/ying/anaconda3/envs/untitled1/lib/python3.6/site-packages/pythainlp/date/__init__.py", line 3, in <module>
    import icu
  File "/Users/ying/anaconda3/envs/untitled1/lib/python3.6/site-packages/icu/__init__.py", line 40, in <module>
    from .docs import *
  File "/Users/ying/anaconda3/envs/untitled1/lib/python3.6/site-packages/icu/docs.py", line 23, in <module>
    from _icu import *
ModuleNotFoundError: No module named '_icu'

**Comment by wannaphongcom** [comment]
Fix in PyThaiNLP 1.5.4.1
``pip install pythainlp -U``
