### ISSUE TITLE
TypeError in pythainlp.spell.symspellpy

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythainlp#650]
## Description

`pythainlp.spell.symspellpy` has error with symspellpy v6.7.6.

```
======================================================================
ERROR: test_correct_sent (test_spell.TestSpellPackage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/test-pythainlp-pip/test-pythainlp-pip/pythainlp_test/pythainlp-3.0.2/tests/test_spell.py", line 133, in test_correct_sent
    correct_sent(self.spell_sent, engine="symspellpy")
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pythainlp/spell/core.py", line 176, in correct_sent
    return spell_sent(list_words, engine=engine)[0]
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pythainlp/spell/core.py", line 141, in spell_sent
    list_new = symspellpy_spell(list_words)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pythainlp/spell/symspellpy.py", line 57, in spell_sent
    max_edit_distance=max_edit_distance
TypeError: lookup_compound() got an unexpected keyword argument 'split_phrase_by_space'

======================================================================
ERROR: test_spell_sent (test_spell.TestSpellPackage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/test-pythainlp-pip/test-pythainlp-pip/pythainlp_test/pythainlp-3.0.2/tests/test_spell.py", line 125, in test_spell_sent
    self.assertIsNotNone(spell_sent(self.spell_sent, engine="symspellpy"))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pythainlp/spell/core.py", line 141, in spell_sent
    list_new = symspellpy_spell(list_words)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pythainlp/spell/symspellpy.py", line 57, in spell_sent
    max_edit_distance=max_edit_distance
TypeError: lookup_compound() got an unexpected keyword argument 'split_phrase_by_space'

----------------------------------------------------------------------
```

**Comment by wannaphong** [comment]
Fixed https://github.com/PyThaiNLP/pythainlp/commit/b403435e12a222c047950499915dea24fb947e2d
