### ISSUE TITLE
bug: Transliteration fails with exception for some strings

### ISSUE THREAD

**Issue by roshats** [PyThaiNLP/pythainlp#759]
### Description

Transliteration raises an `IndexError` exception.

### Expected results

String is transliterated.

### Current results

Exception is raised:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pythainlp/transliterate/core.py", line 59, in romanize
    return romanize(text)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pythainlp/transliterate/royin.py", line 216, in romanize
    romanized_words = [_romanize(word) for word in words]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pythainlp/transliterate/royin.py", line 216, in <listcomp>
    romanized_words = [_romanize(word) for word in words]
                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pythainlp/transliterate/royin.py", line 200, in _romanize
    word = _replace_consonants(word, consonants)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pythainlp/transliterate/royin.py", line 184, in _replace_consonants
    mod_chars.append(_CONSONANTS[consonants[j]][1])
                                 ~~~~~~~~~~^^^
IndexError: list index out of range
```

### Steps to reproduce

Try to transliterate string "โรงเรียนฤทธิยะวรรณาลัย":

```
$ docker run --rm -it --entrypoint /bin/sh python:3.11
# pip install pythainlp==3.1.1
# python
>>> from pythainlp.transliterate import romanize
>>> romanize('โรงเรียนฤทธิยะวรรณาลัย')
```

### PyThaiNLP version

3.1.1

### Python version

3.11

### Operating system and version

Debian 11

**Comment by wannaphong** [comment]
@roshats Thank you for reporting! I checked the bug. The `royin` engine (default engine of `romanize` function) of romanize doesn't supporting word that have many syllables. I recommend you should use `thai2rom` engine instead `royin` engine.

```python
romanize('โรงเรียนฤทธิยะวรรณาลัย',engine="thai2rom")
# output: 'rongrianritthiyawannalai'
```

**Comment by wannaphong** [comment]
You can read the `pythainlp.transliterate` documentation at https://pythainlp.github.io/docs/3.1/api/transliterate.html.

**Comment by wannaphong** [comment]
I will close the issues. If you has new update, you can reopen this issues.
